package_path: .

javascripts:
  app:
    - public/javascripts/material-design-lite-1.1.3.js
    - public/javascripts/jquery-3.0.0.js
    - public/javascripts/app.js
stylesheets:
  app:
    - public/stylesheets/material-design-lite-blue-pink-1.1.3.css
    - public/stylesheets/fonts.css
    - public/stylesheets/app.css
